### ISSUE TITLE
运行时显示资源不足

### ISSUE THREAD

**Issue by JackFodtik** [DuangZhu/MAexp#1]
2024-12-27 12:22:27,422	WARNING trial_executor.py:305 -- Ignore this message if the cluster is autoscaling. You asked for 5.0 cpu and 2.0 gpu per trial, but the cluster only has 72.0 cpu and 1.0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
== Status ==
Current time: 2024-12-27 12:22:28 (running for 00:01:01.00)
Memory usage on this node: 66.6/502.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/72 CPUs, 0/1 GPUs, 0.0/300.95 GiB heap, 0.0/132.97 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/user4/czj/MAexp/vda2c_att_MAexp
Number of trials: 1/1 (1 PENDING)
+--------------------------------------+----------+-------+
| Trial name                           | status   | loc   |
|--------------------------------------+----------+-------|
| VDA2CTrainer_maexp_MAexp_0a2c2_00000 | PENDING  |       |
+--------------------------------------+----------+-------+
作者您好！当我按照您的配置安装好以后，尝试运行python env_v7.py --yaml_file ./yaml/maze.yaml，发现我总是GPU数量不够，我的电脑总共有四块3090，但是总会出现如上问题，您认为是怎么回事，如何解决呢？

**Comment by DuangZhu** [comment]
我看这个错误是只找到了一个GPU，“the cluster only has 72.0 cpu and 1.0 gpu”，可以在执行代码前在命令行输入：export CUDA_VISIBLE_DEVICES=0,1试试能不能成功。

另外您可以看看这个yaml文件：/root/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/ray/ray.yaml，在您的环境中marllib的参数文件，我的是这样的，注意那个num_gpus 和 num_gpus_per_worker：

local_mode: False # True for debug mode only
share_policy: "group" #  individual(separate) / group(division) / all(share)
evaluation_interval: 50000 # evaluate model every 10 training iterations
framework: "torch"
num_workers: 0 # thread number
num_gpus: 1 # gpu to use
num_cpus_per_worker: 5 # cpu allocate to each worker
num_gpus_per_worker: 0.25 # gpu allocate to each worker
checkpoint_freq: 100 # save model every 100 training iterations
checkpoint_end: True # save model at the end of the exp
restore_path: {"model_path": "", "params_path": ""} # load model and params path: 1. resume exp 2. rendering policy
stop_iters: 9999999 # stop training at this iteration
stop_timesteps: 2000000 # stop training at this timesteps
stop_reward: 999999 # stop training at this reward
seed: 5 # ray seed
local_dir: "/remote-home/ums_zhushaohao/new/2024/MAexp/exp_results"

**Comment by JackFodtik** [comment]
> 我看这个错误是只找到了一个GPU，“the cluster only has 72.0 cpu and 1.0 gpu”，可以在执行代码前在命令行输入：export CUDA_VISIBLE_DEVICES=0,1试试能不能成功。
> 
> 另外您可以看看这个yaml文件：/root/anaconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/ray/ray.yaml，在您的环境中marllib的参数文件，我的是这样的，注意那个num_gpus 和 num_gpus_per_worker：
> 
> local_mode: False # True for debug mode only share_policy: "group" # individual(separate) / group(division) / all(share) evaluation_interval: 50000 # evaluate model every 10 training iterations framework: "torch" num_workers: 0 # thread number num_gpus: 1 # gpu to use num_cpus_per_worker: 5 # cpu allocate to each worker num_gpus_per_worker: 0.25 # gpu allocate to each worker checkpoint_freq: 100 # save model every 100 training iterations checkpoint_end: True # save model at the end of the exp restore_path: {"model_path": "", "params_path": ""} # load model and params path: 1. resume exp 2. rendering policy stop_iters: 9999999 # stop training at this iteration stop_timesteps: 2000000 # stop training at this timesteps stop_reward: 999999 # stop training at this reward seed: 5 # ray seed local_dir: "/remote-home/ums_zhushaohao/new/2024/MAexp/exp_results"

感谢您的回答！在执行代码前在命令行输入：export CUDA_VISIBLE_DEVICES=0,1试试能不能成功。

**Comment by JackFodtik** [comment]
感谢您的回复！
当我在执行代码前在命令行输入：export CUDA_VISIBLE_DEVICES=0,1后，仍然不行。

当我修改num_gpus和num_gpus_per_worker两个参数时，num_gpus。
在这里的报错中You asked for 5.0 cpu and **2.0 gpu** per trial, but the cluster only has 72.0 cpu and **1.0 gpu**.
当我保持num_gpus_per_worker数量不变，修改num_gpus参数时候，asked的GPU总是比cluster has的GPU数量多1。
当我保持num_gpus数量不变，修改num_gpus_per_worker参数时候，asked的GPU总是比cluster has的GPU数量多，多出来的数量刚好等于num_workers * num_gpus_per_worker
申请的GPU数量等于num_gpus + num_workers * num_gpus_per_worker.

以下是我修改num_gpus=4，num_gpus_per_worker=0.25，num_workers =4，并执行了export CUDA_VISIBLE_DEVICES=0,1,2,3后的情况
2024-12-28 17:21:55,674	WARNING trial_executor.py:305 -- Ignore this message if the cluster is autoscaling. You asked for 5.0 cpu and 5.0 gpu per trial, but the cluster only has 72.0 cpu and 4.0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
== Status ==
Current time: 2024-12-28 17:21:56 (running for 00:01:01.04)
Memory usage on this node: 56.8/502.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/72 CPUs, 0/4 GPUs, 0.0/309.04 GiB heap, 0.0/136.44 GiB objects (0.0/1.0 accelerator_type:G)

**Comment by DuangZhu** [comment]
”num_gpus=4“这个参数改成1再试试可以吗 ，应该在您现在的参数下，把这个改成1就可以了。
或者把num_gpus=4改成3应该也没问题，因为这个数是不算占用模型的GPU的，相当于采样3个GPU，模型需要放在剩下那个GPU。

“You asked for 5.0 cpu and 5.0 gpu per trial”，这里显示的意思是这个程序需要5个gpu,原因就是这里的四个（num_gpus=4）,还有储存网络的一个。
他的参数条件是num_gpu>=num_workers * num_gpus_per_worker，然后再加上一个放模型的GPU，所以最后ask for GPU的数量会是num_gpus+1.

**Comment by JackFodtik** [comment]
感谢您的回复！
